database/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
import os

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('django.contrib.auth.urls')),
                  path('home/', include('robots.urls')),
                  path('', include('robots.urls')),
                  path('changelogs/', include('changelog.urls')),
                  path('timetable/', include('timetable.urls')),
                  #path('', lambda request: redirect('home/', permanent=True)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robots/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('arm/create', ArmCreateView.as_view(), name='arm_create'),
    path('arm/update/<int:pk>', ArmUpdateView.as_view(), name='arm_update'),
    path('arm/delete/<int:pk>', ArmDeleteView.as_view(), name='arm_delete'),
    path('arm/list/', ArmListView.as_view(), name='arm_list'),
    #
    path('backup/create', BackupCreateView.as_view(), name='backup_create'),
    path('backup/delete/<int:pk>', BackupDeleteView.as_view(), name='backup_delete'),
    #
    path('client/create', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client/list/', ClientListView.as_view(), name='client_list'),
    #
    path('controller/create', ControllerCreateView.as_view(), name='controller_create'),
    path('controller/update/<int:pk>', ControllerUpdateView.as_view(), name='controller_update'),
    path('controller/delete/<int:pk>', ControllerDeleteView.as_view(), name='controller_delete'),
    path('controller/list/', ControllerListView.as_view(), name='controller_list'),
    #
    path('integrator/create', IntegratorCreateView.as_view(), name='integrator_create'),
    path('integrator/update/<int:pk>', IntegratorUpdateView.as_view(), name='integrator_update'),
    path('integrator/delete/<int:pk>', IntegratorDeleteView.as_view(), name='integrator_delete'),
    path('integrator/list/', IntegratorListView.as_view(), name='integrator_list'),
    #
    path('location/create', LocationCreateView.as_view(), name='location_create'),
    path('location/update/<int:pk>', LocationUpdateView.as_view(), name='location_update'),
    path('location/delete/<int:pk>', LocationDeleteView.as_view(), name='location_delete'),
    path('location/list/', LocationListView.as_view(), name='location_list'),
    #
    path('robot/create', RobotCreateView.as_view(), name='robot_create'),
    path('robot/read/<int:pk>', RobotReadView.as_view(), name='robot_read'),
    path('robot/update/<int:pk>', RobotUpdateView.as_view(), name='robot_update'),
    path('robot/delete/<int:pk>', RobotDeleteView.as_view(), name='robot_delete'),
    #
    path('service/create/<int:pk>', ServiceCreateView.as_view(), name='service_create'),
    path('service/update/<int:pk>', ServiceUpdateView.as_view(), name='service_update'),
    path('service/delete/<int:pk>', ServiceDeleteView.as_view(), name='service_delete'),
]

timetable/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', StaffListView.as_view(), name='staff_list'),
    path('d', StaffDetailView.as_view(), name='staff_detail'),
]

timetable/models.py
from django.db import models
from users.models import RobowizardEmployee


class WorkingPlace(models.Model):
    name = models.CharField(verbose_name='Название', max_length=255)

    def __str__(self):
        return self.name


class WorkingDay(models.Model):
    date = models.DateField(verbose_name='Дата')
    employee = models.ForeignKey(RobowizardEmployee, on_delete=models.DO_NOTHING, verbose_name='Работник')

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")

    def get_workingdayparts(self):
        return WorkingDayPart.objects.filter(workingday_id=self.id)

    @property
    def get_number_of_workingdayparts(self):
        return WorkingDayPart.objects.filter(workingday_id_id=self.id)

    @property
    def get_maxworkingdaypartsnumber(self):
        max = 0
        for obj in WorkingDayPart.objects.filter(workingday_id_id=self.id):
            if len(obj) > max:
                max = len(obj)
        return  max

    # def all_workingdayparts(self):
    #     return WorkingDayPart.objects.all()


class WorkingDayPart(models.Model):
    workingday_id = models.ForeignKey(WorkingDay, on_delete=models.DO_NOTHING, verbose_name='Дата')
    begin_time = models.TimeField(verbose_name='Начало')
    end_time = models.TimeField(verbose_name='Конец')
    location_id = models.ForeignKey(WorkingPlace, verbose_name='Место', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.begin_time.strftime('%H:%M') + "-" + self.end_time.strftime('%H:%M')

timetable/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from .models import *
from django.template.defaulttags import register


class StaffListView(LoginRequiredMixin, ListView):
    model = WorkingDay
    template_name = 'timetable/staff_list.html'
    login_url = 'login'

    @staticmethod
    def all_workingdayparts():
        return WorkingDayPart.objects.all()

    @staticmethod
    def all_workingplaces():
        return WorkingPlace.objects.all()


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = WorkingDay

templates/timetable/staff_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Табель{% endblock title %}
{% block content %}
    {% for workingday in workingday_list %}
        {% if request.user.id == workingday.employee_id %}
            <h3>{{ workingday.date }}</h3>
            <h3>{{ workingday.employee_id }}</h3>
            <h3>Visits</h3>
            {% for workingdaypart in view.all_workingdayparts %}
                {% if workingdaypart.workingday_id_id == workingday.pk %}
                    <p>{{ workingdaypart }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
    <table id="info-table" class="table table-robot-list table-sort">
        <thead class="thead-default">
        <tr>
            {% load my_filters %}
            {% for i in 48|get_range %}
                <th>{{ i }}|get_time_by_id</th>
            {% endfor %}
        </tr>
        <tr>
            {% for i in 24|get_range %}
                <th>+</th>
            {% endfor %}
        </tr>
        </thead>
    </table>
{% endblock content %}

templates/timetable/staff_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load my_filters %}
{% block title %}Табель{% endblock title %}
{% block content %}
    {% for workingday in workingday_list %}
        {% if request.user.id == workingday.employee_id %}
            <h3>{{ workingday.date }}</h3>
            <h3>{{ workingday.employee_id }}</h3>
            <h3>Visits</h3>
            {% for workingdaypart in view.all_workingdayparts %}
                {% if workingdaypart.workingday_id_id == workingday.pk %}
                    <p>{{ workingdaypart }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
    <table class="table">
        <thead class="thead-default">
        <tr>
            <th style="width: 130px">Дата:</th>
            <th style="text-align: center; vertical-align: middle;" colspan="{{ view.all_workingdayparts|length }}">Время</th>
        </tr>
        </thead>
        <tbody>
        {% for workingday in workingday_list %}
            <tr>
                <th>{{ workingday.date }}</th>
                {% for workingdaypart in workingday.get_workingdayparts %}
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}