database/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
import os

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('django.contrib.auth.urls')),
                  path('home/', include('robots.urls')),
                  path('', include('robots.urls')),
                  path('changelogs/', include('changelog.urls')),
                  path('timetable/', include('timetable.urls')),
                  #path('', lambda request: redirect('home/', permanent=True)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robots/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('arm/create', ArmCreateView.as_view(), name='arm_create'),
    path('arm/update/<int:pk>', ArmUpdateView.as_view(), name='arm_update'),
    path('arm/delete/<int:pk>', ArmDeleteView.as_view(), name='arm_delete'),
    path('arm/list/', ArmListView.as_view(), name='arm_list'),
    #
    path('backup/create', BackupCreateView.as_view(), name='backup_create'),
    path('backup/delete/<int:pk>', BackupDeleteView.as_view(), name='backup_delete'),
    #
    path('client/create', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client/list/', ClientListView.as_view(), name='client_list'),
    #
    path('controller/create', ControllerCreateView.as_view(), name='controller_create'),
    path('controller/update/<int:pk>', ControllerUpdateView.as_view(), name='controller_update'),
    path('controller/delete/<int:pk>', ControllerDeleteView.as_view(), name='controller_delete'),
    path('controller/list/', ControllerListView.as_view(), name='controller_list'),
    #
    path('integrator/create', IntegratorCreateView.as_view(), name='integrator_create'),
    path('integrator/update/<int:pk>', IntegratorUpdateView.as_view(), name='integrator_update'),
    path('integrator/delete/<int:pk>', IntegratorDeleteView.as_view(), name='integrator_delete'),
    path('integrator/list/', IntegratorListView.as_view(), name='integrator_list'),
    #
    path('location/create', LocationCreateView.as_view(), name='location_create'),
    path('location/update/<int:pk>', LocationUpdateView.as_view(), name='location_update'),
    path('location/delete/<int:pk>', LocationDeleteView.as_view(), name='location_delete'),
    path('location/list/', LocationListView.as_view(), name='location_list'),
    #
    path('robot/create', RobotCreateView.as_view(), name='robot_create'),
    path('robot/read/<int:pk>', RobotReadView.as_view(), name='robot_read'),
    path('robot/update/<int:pk>', RobotUpdateView.as_view(), name='robot_update'),
    path('robot/delete/<int:pk>', RobotDeleteView.as_view(), name='robot_delete'),
    #
    path('service/create/<int:pk>', ServiceCreateView.as_view(), name='service_create'),
    path('service/update/<int:pk>', ServiceUpdateView.as_view(), name='service_update'),
    path('service/delete/<int:pk>', ServiceDeleteView.as_view(), name='service_delete'),
]

robots/models.py
from django.db import models
from django.db.models.signals import post_delete, post_save

from changelog.mixins import ChangeloggableMixin
from changelog.signals import journal_save_handler, journal_delete_handler


class Robot(ChangeloggableMixin, models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name='Имя',
    )

    # Текстовое поле из-за ниличия серийных номеров с буквой С
    serial_number = models.CharField(
        max_length=32,
        verbose_name='Серийный номер',
    )

    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True,
    )

    shipping_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='Дата поставки', )

    creation_date = models.DateField(
        auto_now=True,
    )

    controller_id = models.ForeignKey(
        'Controller',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Контроллер',
    )

    model_id = models.ForeignKey(
        'Arm',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Модель',
    )

    client_id = models.ForeignKey(
        'Client',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Клиент',
    )

    integrator_id = models.ForeignKey(
        'Integrator',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Интегратор',
        blank=True,
    )

    main_backup_file = models.FileField(
        verbose_name='Бэкап',
        null=True,
        blank=True,
        upload_to='backups/'
    )

    def __str__(self):
        return self.name


class Arm(ChangeloggableMixin, models.Model):
    name = models.CharField(
        max_length=32,
        unique=True,
        verbose_name="Модель",
    )

    def __str__(self):
        return self.name


class Controller(ChangeloggableMixin, models.Model):
    name = models.CharField(
        max_length=32,
        unique=True,
        verbose_name="Контроллер",
    )

    def __str__(self):
        return self.name


class Client(ChangeloggableMixin, models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name="Клиент",
        unique=True,
    )

    location_id = models.ForeignKey(
        'Location',
        on_delete=models.DO_NOTHING,
        verbose_name='Местоположение',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name


# Интегратор
class Integrator(ChangeloggableMixin, models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name="Интегратор",
        unique=True,
    )

    location_id = models.ForeignKey(
        'Location',
        on_delete=models.DO_NOTHING,
        verbose_name='Местоположение',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name


class Location(ChangeloggableMixin, models.Model):
    country = models.CharField(
        max_length=255,
        verbose_name='Страна',
    )

    city = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Город',
    )

    def __str__(self):
        return self.country + "/" + self.city


class Backup(ChangeloggableMixin, models.Model):
    file = models.FileField(
        verbose_name='Файл',
        upload_to='backups/',
        # # Временно, пока не обеспечу загрузку файлов
        # blank=True,
        # null=True,
    )

    service_id = models.ForeignKey(
        'Service',
        on_delete=models.DO_NOTHING
    )
    comment = models.TextField(
        verbose_name='Комментарий',
        null=True,
        blank=True,
    )

    def __str__(self):
        return "Backup" + str(self.id)


class Service(ChangeloggableMixin, models.Model):
    date = models.DateField(
        verbose_name='Дата',
    )
    report = models.FileField(
        null=True,
        blank=True,
        upload_to='reports/',
        verbose_name='Отчёт',
    )

    description = models.TextField(
        verbose_name='Описание',
    )

    robot_id = models.ForeignKey(
        'Robot',
        on_delete=models.CASCADE,
        verbose_name='Робот',
    )

    def __str__(self):
        return self.description

    @property
    def days_from_service(self):
        from datetime import datetime
        date_format = "%Y-%m-%d"
        a = datetime.strptime(str(datetime.now().date()), date_format)
        b = datetime.strptime(str(self.date), date_format)
        delta = b - a
        if delta.days < 0:
            return str(-delta.days) + ' дней назад'
        else:
            return 'Запланировано на ' + str(self.date.strftime("%d.%m.%Y")) + ' (через ' + str(
                delta.days) + ' дня(ей))'


post_save.connect(journal_save_handler, sender=Robot)
post_delete.connect(journal_delete_handler, sender=Robot)

#
post_save.connect(journal_save_handler, sender=Arm)
post_delete.connect(journal_delete_handler, sender=Arm)
#
post_save.connect(journal_save_handler, sender=Backup)
post_delete.connect(journal_delete_handler, sender=Backup)
#
post_save.connect(journal_save_handler, sender=Client)
post_delete.connect(journal_delete_handler, sender=Client)
#
post_save.connect(journal_save_handler, sender=Controller)
post_delete.connect(journal_delete_handler, sender=Controller)
#
post_save.connect(journal_save_handler, sender=Integrator)
post_delete.connect(journal_delete_handler, sender=Integrator)
#
post_save.connect(journal_save_handler, sender=Location)
post_delete.connect(journal_delete_handler, sender=Location)
#
post_save.connect(journal_save_handler, sender=Service)
post_delete.connect(journal_delete_handler, sender=Service)

robots/views.py
from .subviews import *


class HomePageView(LoginRequiredMixin, ListView):
    model = Robot
    template_name = 'robots/home.html'
    login_url = 'login'

templates/robots/robot/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Добавить робота{% endblock title %}
{% block content %}
    <script src="{% static 'robots/js/update.js' %}"></script>
    <div class="container">
        <h1>Добавить робота</h1><br>
        <form enctype="multipart/form-data" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="name col-md-8">{{ form.name|as_crispy_field }}</div>
                <div class="col-md-4">{{ form.serial_number|as_crispy_field }}</div>
            </div>
            <div class="row">
                <div class="col-md-12">{{ form.description|as_crispy_field }}</div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-8">{{ form.controller_id|as_crispy_field }}</div>
                        <div class="col-md-4"><a href="{% url 'controller_create' %}"
                                                 onclick="return showAddPopup(this);">Новый контроллер</a></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-8">{{ form.model_id|as_crispy_field }}</div>
                        <div class="col-md-4"><a href="{% url 'arm_create' %}" onclick="return showAddPopup(this);">Новая модель</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-8">{{ form.client_id|as_crispy_field }}</div>
                        {% comment %}<a href="{% url 'client_create' %}" id="add_author"
                           onclick="return showAddPopup(this);">+++++</a>{% endcomment %}
                        <div class="col-md-4"><a href="{% url 'client_create' %}" onclick="return showAddPopup(this);">Новый клиент</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-8">{{ form.integrator_id|as_crispy_field }}</div>
                        <div  class="col-md-4"><a href="{% url 'integrator_create' %}"
                                                 onclick="return showAddPopup(this);">Новый интегратор</a></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="description col-md-2">
                    {{ form.shipping_date|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="description col-md-8">
                    {{ form.main_backup_file|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="button col-md-12">
                    <button type="submit" class="btn btn-primary"
                            style="position: absolute; right: 10px">Создать
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script>
        $('#id_shipping_date').datetimepicker({
            format: 'd.m.Y',
            timepicker: false,
        });
    </script>
{% endblock content %}

templates/robots/robot/read.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Robot list{% endblock title %}
{% block content %}
    <div class="container" style="-moz-hyphens: auto; -webkit-hyphens: auto; -ms-hyphens: auto;">
        <table class="button-forms">
            <tr>
                <td>
                    <form class="pt-1" action="{% url 'home' %}" target="_self">
                        <button style="font-size: large;" class="btn btn-primary">Назад</button>
                    </form>
                </td>
                <td>
                    <form class="pt-1" action="{% url 'robot_update' robot.pk %}" target="_self">
                        <button style="font-size: large;" class="btn btn-success">Изменить</button>
                    </form>
                </td>
                <td>
                    <form class="pt-1" action="{% url 'robot_delete' robot.pk %}" target="_self">
                        <button style="font-size: large;" class="btn btn-danger">Удалить</button>
                    </form>
                </td>
            </tr>
        </table>
        {% comment %}<h1 class="pt-1">Информация о роботе:</h1>
        <table class="table" style="font-size: large;">
            <thead class="thead-default">
            <tr>
                <th>Имя</th>
                <th>Серийный номер</th>
                <th>Модель</th>
                <th>Клиент</th>
                <th>Контроллер</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th><a href="{% url 'robot_read' robot.pk %}">{{ object.name }}</a></th>
                <th>{{ object.serial_number }}</th>
                <th>{{ object.model_id }}</th>
                <th>{{ object.client_id }}</th>
                <th>{{ object.controller_id }}</th>
            </tr>
            </tbody>
        </table>{% endcomment %}

        {#        <p style="font-size: large;">id: {{ object.id }}</p>#}
        <h5>Имя робота: {{ object.name }}</h5>
        <h5>Серийный номер: {{ object.serial_number }}</h5>
        <div style="word-wrap: normal;">
            <h5 >Описание:<br/></h5>
            <div class="text-muted">{{ object.description }}</div>
        </div>

        <h5>Дата поставки: {{ object.shipping_date }}</h5>
        <h5>Дата создания объекта в базе: {{ object.creation_date }}</h5>
        <h5>Контроллер: {{ object.controller_id }}</h5>
        <h5>Модель: {{ object.model_id }}</h5>
        <h5>Клиент: {{ object.client_id }}</h5>
        <h5>Интегратор: {{ object.integrator_id }}</h5>
        {% if object.main_backup_file %}
            <p style="font-size: large;"><a
                    href="{% url 'home' %}media/{{ object.main_backup_file }}">Основная резервная копия</a></p>
        {% endif %}


        <h1>Обслуживания: <a style="font-size: 18pt;" href="{% url 'service_create' pk=robot.pk %}">Добавить</a></h1>
        {% for service in object.service_set.all %}
            <div class="card">
                <div class="card-header">
                    <span class="font-weight-bold">{{ service.date }}</span> &middot;
                    <span class="text-muted"> {{ service.days_from_service }}</span>
                </div>
                <div class="card-body">
                    {{ service.description }}
                    {% if service.report %}
                        <p class="lead"><a href="{% url 'home' %}media/{{ service.report }}">Отчёт</a></p>
                    {% endif %}
                </div>
                <div class="card-footer text-center text-muted">
                    <a href="{% url 'service_update' service.pk %}">Изменить</a> | <a
                        href="{% url 'service_delete' service.pk %}">Удалить</a>
                </div>
            </div>
            <br/>
        {% endfor %}
    </div>
{% endblock content %}

templates/robots/robot/update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Изменить робота{% endblock title %}
{% block content %}
    <script src="{% static 'robots/js/update.js' %}"></script>
    <div class="container">
        <h1>Изменить робота</h1><br>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="name col-md-8">{{ form.name|as_crispy_field }}</div>
                <div class="col-md-4">{{ form.serial_number|as_crispy_field }}</div>
            </div>
            <div class="row">
                <div class="col-md-12">{{ form.description|as_crispy_field }}</div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">{{ form.controller_id|as_crispy_field }}</div>
                        <div class="col-md-2"><a href="{% url 'controller_create' %}"
                                                 onclick="return showAddPopup(this);">Добавить</a></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">{{ form.model_id|as_crispy_field }}</div>
                        <div class="col-md-2"><a href="{% url 'arm_create' %}" onclick="return showAddPopup(this);">Добавить</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">{{ form.client_id|as_crispy_field }}</div>
                        {% comment %}<a href="{% url 'client_create' %}" id="add_author"
                           onclick="return showAddPopup(this);">+++++</a>{% endcomment %}
                        <div class="col-md-2"><a href="{% url 'client_create' %}" onclick="return showAddPopup(this);">Добавить</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="col-md-10">{{ form.integrator_id|as_crispy_field }}</div>
                        <div class="col-md-2"><a href="{% url 'integrator_create' %}"
                                                 onclick="return showAddPopup(this);">Добавить</a></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="description col-md-2">
                    {{ form.shipping_date|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="description col-md-8">
                    {{ form.main_backup_file|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="button col-md-12">
                    <button onclick=clearStorage() type="submit" class="btn btn-primary"
                            style="position: absolute; right: 10px">Изменить
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script>
        $('#id_shipping_date').datetimepicker({
            format: 'd.m.Y',
            timepicker: false,
        });
    </script>
{% endblock content %}